version: "3"
services:
  pig:
    build: .
    container_name: pig
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FERNET_KEY=${FERNET_KEY}
    volumes:
      - pig-data:/app/data

volumes:
  pig-data:
